export const ADD_ORDERS = 'ADD_ORDERS';
export const ORDERS_LOADING = 'ORDERS_LOADING';
export const ORDERS_FAILED = 'ORDERS_FAILED';
export const ADD_ORDER = 'ADD_ORDER';
export const FIND_ORDER = 'FIND_ORDER';

export const ADD_SANDWICHES = 'ADD_SANDWICHES';
export const SANDWICHES_LOADING = 'SANDWICHES_LOADING';
export const SANDWICHES_FAILED = 'SANDWICHES_FAILED';

